export class DocumentGenerator {
  static generateInspectionId(): string {
    const date = new Date();
    const dateStr = date.toISOString().split('T')[0].replace(/-/g, '');
    const timeStr = date.getHours().toString().padStart(2, '0') + 
                   date.getMinutes().toString().padStart(2, '0');
    return `ADUI-${dateStr}-${timeStr}`;
  }

  static generateReportContent(
    documentId: string, 
    windowName: string, 
    formData: Record<string, any>, 
    location: any,
    tabs: any[]
  ): { subject: string; body: string } {
    const subject = `${documentId} - ${windowName}`;
    
    let body = `${windowName.toUpperCase()} REPORT
==========================================
Document ID: ${documentId}
Date: ${new Date().toLocaleString()}
Location: ${location ? 
  `${location.latitude.toFixed(6)}, ${location.longitude.toFixed(6)} (±${location.accuracy?.toFixed(0)}m)` : 
  'Location not available'}

FORM DATA:
`;

    // Add form data by tabs
    tabs.forEach(tab => {
      body += `\n${tab.name.toUpperCase()}:\n`;
      tab.fields.forEach((field: any) => {
        const value = formData[field.id];
        if (value?.display || value?.raw) {
          body += `${field.name}: ${value.display || value.raw}\n`;
        }
      });
    });

    body += `\nGenerated by ADUI - AD-Driven Mobile Forms v1.0`;
    
    return { subject, body };
  }
}
